name: Build YASK Kernel
on:
  workflow_dispatch:
    inputs:
      kernelDevice:
        description: 'Device codename'
        required: true
        default: 'sapphire'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev libelf-dev
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r584948b.tar.gz
        mkdir -p clang
        tar -xzf clang-r584948b.tar.gz -C clang
        echo "$PWD/clang/bin" >> $GITHUB_PATH
        
    - name: Build kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        make vendor/bengal_GKI.config
        make -j$(nproc)
        
    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: Image
        path: arch/arm64/boot/Image.gz
