name: Build Kernel
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev libelf-dev gcc-aarch64-linux-gnu
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make vendor/bengal_GKI.config
        make -j$(nproc)
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: kernel
        path: arch/arm64/boot/Image.gz
